# Generated by Django 2.1.5 on 2019-04-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='size',
            new_name='size_Or_Power',
        ),
    ]
