# Generated by Django 2.1.5 on 2019-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent',
            name='tent_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
